name: Publish to NPM
on:
    release:
        types: [created]
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup Node
          uses: oven-sh/setup-bun@v2
          with:
            bun-version: 'latest'
            registry-url: 'https://registry.npmjs.org'
        - name: Install dependencies
          run: bun install
        - name: Publish package on NPM
          run: bun publish
          env:
            NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}